"""
leos.atmosphere_mars
---------------------
Mars-specific atmospheric column data: altitude-resolved T(z), P(z),
n(z), and per-species volume mixing ratios vmr_i(z).

Two tiers of data:

Tier 1 (always available, no download)
    AtmosphericColumnMars.from_bundled(ls, lat, dust) — loads one of
    the 36 pre-computed MCD v6.1 profiles bundled in
    leos/data/mcd_bundled_profiles.npz. Covers 4 seasons x 3 latitude
    bands x 3 dust scenarios. Nearest-neighbor selection in Ls/lat
    space; dust scenario by label ('avg', 'warm', 'cold').

Tier 2 (live web API, requires internet)
    AtmosphericColumnMars.from_webapi(ls, lat, lon, dust, vars) —
    queries the LMD MCD v6.1 web interface directly via
    scripts/convert_mcd_webapi.py logic. Slower (~2 min per profile)
    but gives any lat/lon/Ls combination and all MCD variables.

In both cases, AtmosphericColumnMars provides the same interface as
AtmosphericColumn in atmosphere_earth.py:
    column_density(species)      — Ni = integral(xi(z)*n(z) dz)
    scale_height_at(z_km)        — local H(z)
    effective_scale_height()     — density-weighted H for Chapman
    to_profile(**overrides)      — AtmosphericProfile for RT module

The MCD bundled profiles contain all variables queried during
generation — T, P, rho, VMRs for CO2/N2/Ar/CO/O2/O3/H2O, dust tau
(tauref, dod), solar fluxes, surface conditions, thermodynamic
properties (Cp, Rgas, pscaleheight), and RMS variability (rmst).
"""

import os
import warnings
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

import numpy as np
from astropy import units as u

from .atmosphere import AtmosphericProfile

# ── Physical constants ────────────────────────────────────────────────────────
_kB          = 1.380649e-23   # J/K
_g_mars      = 3.721          # m/s^2
_R_MARS_KM   = 3390.0         # km

_MOLECULAR_MASS_KG = AtmosphericProfile._MOLECULAR_MASS_KG

# ── Bundled profile path ──────────────────────────────────────────────────────
_BUNDLE_PATH = os.path.join(
    os.path.dirname(__file__), "data", "mcd_bundled_profiles.npz"
)

# ── Bundled profile grid ──────────────────────────────────────────────────────
_BUNDLED_LS    = [0, 90, 180, 270]
_BUNDLED_LATS  = [0, 45, 75]
_BUNDLED_DUSTS = {
    1: "avg",
    7: "warm",
    8: "cold",
}
_DUST_LABEL_TO_CODE = {v: k for k, v in _BUNDLED_DUSTS.items()}


# ══════════════════════════════════════════════════════════════════════════════
# Source registry
# ══════════════════════════════════════════════════════════════════════════════

class MarsAtmosphericSource(Enum):
    MCD_BUNDLED = "mcd_bundled"   # 36 pre-computed profiles, always available
    MCD_WEBAPI  = "mcd_webapi"    # live LMD web API query
    CUSTOM      = "custom"        # user-supplied arrays or npz


MARS_ATMO_REGISTRY = {
    MarsAtmosphericSource.MCD_BUNDLED: {
        "description": (
            "MCD v6.1 bundled profiles: 4 seasons (Ls=0/90/180/270) x "
            "3 latitude bands (0/45/75 N) x 3 dust scenarios "
            "(avg=code1, warm=code7, cold=code8). "
            "22 pressure levels, 0-93 km. All MCD variables included. "
            "Generated by scripts/convert_mcd_webapi.py."
        ),
        "reference": (
            "Forget et al. (1999), J. Geophys. Res. 104, 24155-24175. "
            "Millour et al. (2015), European Planetary Science Congress."
        ),
        "requires_download": False,
    },
    MarsAtmosphericSource.MCD_WEBAPI: {
        "description": (
            "Live query to LMD MCD v6.1 web interface. "
            "Any lat/lon/Ls/dust combination. ~2 min per profile."
        ),
        "reference": "https://www-mars.lmd.jussieu.fr/mcd_python/",
        "requires_download": False,
    },
    MarsAtmosphericSource.CUSTOM: {
        "description": "User-supplied column arrays or .npz file.",
        "reference": "User-supplied data.",
        "requires_download": False,
    },
}


# ══════════════════════════════════════════════════════════════════════════════
# AtmosphericColumnMars
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class AtmosphericColumnMars:
    """
    Altitude-resolved Mars atmospheric column.

    Parameters
    ----------
    z_km : np.ndarray
        Altitude grid, ascending, km (above areoid).
    T_K : np.ndarray
        Temperature, K.
    P_Pa : np.ndarray
        Pressure, Pa.
    vmr : dict[str, np.ndarray]
        Volume mixing ratio profiles. Keys are species names
        (e.g. 'CO2', 'N2', 'O3', 'H2O') or MCD variable codes
        (e.g. 'vmr_co2' stored without the 'vmr_' prefix here).
    n_total : np.ndarray, optional
        Total number density, molecules/m^3. Computed from ideal gas
        law if not provided.
    sigma_T : np.ndarray, optional
        Temperature 1-sigma uncertainty, K (MCD rmst if available).
    tauref : float, optional
        Daily mean visible dust optical depth (610 Pa reference).
    dod : float, optional
        Monthly mean visible dust optical depth.
    tsurf_K : float, optional
        Surface temperature, K.
    ps_Pa : float, optional
        Surface pressure, Pa.
    fluxsurf_dn_sw : float, optional
        Downward solar flux at surface, W/m^2.
    fluxtop_dn_sw : float, optional
        Downward solar flux at TOA, W/m^2.
    ls : float, optional
        Solar longitude, degrees.
    lat, lon : float, optional
        Location, degrees.
    dust_code : int, optional
        MCD dust scenario code (1=avg, 7=warm, 8=cold).
    dust_label : str, optional
        Human-readable dust label.
    source : MarsAtmosphericSource
    extra : dict
        Any additional MCD scalar or array variables (Cp, Rgas,
        pscaleheight, col_co2, col_o3, col_h2ovapor, rho, ...).
    """

    z_km           : np.ndarray
    T_K            : np.ndarray
    P_Pa           : np.ndarray
    vmr            : dict = field(default_factory=dict)
    n_total        : Optional[np.ndarray] = None
    sigma_T        : Optional[np.ndarray] = None
    tauref         : Optional[float] = None
    dod            : Optional[float] = None
    tsurf_K        : Optional[float] = None
    ps_Pa          : Optional[float] = None
    fluxsurf_dn_sw : Optional[float] = None
    fluxtop_dn_sw  : Optional[float] = None
    ls             : Optional[float] = None
    lat            : Optional[float] = None
    lon            : Optional[float] = None
    dust_code      : Optional[int]   = None
    dust_label     : Optional[str]   = None
    source         : MarsAtmosphericSource = MarsAtmosphericSource.CUSTOM
    extra          : dict = field(default_factory=dict)

    def __post_init__(self):
        self.z_km   = np.asarray(self.z_km,   dtype=float)
        self.T_K    = np.asarray(self.T_K,    dtype=float)
        self.P_Pa   = np.asarray(self.P_Pa,   dtype=float)

        # Sort ascending by altitude
        order = np.argsort(self.z_km)
        if not np.all(order == np.arange(len(order))):
            self.z_km = self.z_km[order]
            self.T_K  = self.T_K[order]
            self.P_Pa = self.P_Pa[order]
            if self.n_total is not None:
                self.n_total = np.asarray(self.n_total)[order]
            if self.sigma_T is not None:
                self.sigma_T = np.asarray(self.sigma_T)[order]
            for k in list(self.vmr):
                self.vmr[k] = np.asarray(self.vmr[k])[order]

        if self.n_total is None:
            self.n_total = self.P_Pa / (_kB * self.T_K)
        else:
            self.n_total = np.asarray(self.n_total, dtype=float)

        for k in list(self.vmr):
            self.vmr[k] = np.asarray(self.vmr[k], dtype=float)

    def __str__(self):
        dust_str = (f"  dust={self.dust_label}(code={self.dust_code})"
                    if self.dust_label else "")
        ls_str   = f"  Ls={self.ls:.0f}°" if self.ls is not None else ""
        tau_str  = f"  tauref={self.tauref:.3f}" if self.tauref is not None else ""
        return (
            f"AtmosphericColumnMars: {self.source.value}"
            f"{ls_str}{dust_str}{tau_str} | "
            f"{len(self.z_km)} levels, "
            f"{self.z_km[0]:.1f}-{self.z_km[-1]:.1f} km | "
            f"T {self.T_K.min():.1f}-{self.T_K.max():.1f} K"
        )

    def __repr__(self):
        return self.__str__()

    # ══════════════════════════════════════════════════════════════════════════
    # Loaders
    # ══════════════════════════════════════════════════════════════════════════

    @classmethod
    def from_bundled(
        cls,
        ls: float,
        lat: float,
        dust: str = "avg",
        bundle_path: Optional[str] = None,
    ) -> "AtmosphericColumnMars":
        """
        Load the nearest bundled MCD profile.

        Nearest-neighbor selection in (Ls, lat) space. Dust scenario
        selected by label ('avg', 'warm', 'cold').

        Parameters
        ----------
        ls : float
            Solar longitude, degrees [0, 360).
        lat : float
            Latitude, degrees [-90, 90].
        dust : str
            Dust scenario: 'avg' (code 1), 'warm' (code 7),
            'cold' (code 8). Default 'avg'.
        bundle_path : str, optional
            Override default bundle path.

        Returns
        -------
        AtmosphericColumnMars
        """
        path = bundle_path or _BUNDLE_PATH
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"MCD bundled profiles not found: {path}\n"
                f"Run: python scripts/convert_mcd_webapi.py --generate-bundled"
            )

        dust = dust.lower().strip()
        if dust not in _DUST_LABEL_TO_CODE:
            raise ValueError(
                f"Unknown dust label '{dust}'. "
                f"Choose from: {list(_DUST_LABEL_TO_CODE.keys())}"
            )
        dust_code = _DUST_LABEL_TO_CODE[dust]

        # Nearest-neighbor in Ls and lat
        ls_nn  = min(_BUNDLED_LS,   key=lambda x: abs(x - ls))
        lat_nn = min(_BUNDLED_LATS, key=lambda x: abs(x - lat))

        key = f"Ls{ls_nn:03d}_lat+{lat_nn:02d}_dust{dust_code}"

        d = np.load(path, allow_pickle=True)

        if f"{key}__z_km" not in d:
            raise KeyError(
                f"Profile key '{key}' not found in bundle. "
                f"Available keys: {list(d['profile_keys'])}"
            )

        if abs(ls - ls_nn) > 45 or abs(lat - lat_nn) > 22.5:
            warnings.warn(
                f"Requested (Ls={ls}, lat={lat}) is far from nearest "
                f"bundled profile (Ls={ls_nn}, lat={lat_nn}). "
                f"Consider using from_webapi() for exact coordinates.",
                UserWarning,
            )

        return cls._from_bundle_key(d, key, dust_code, dust)

    @classmethod
    def _from_bundle_key(
        cls, d, key: str, dust_code: int, dust_label: str
    ) -> "AtmosphericColumnMars":
        """Internal: build AtmosphericColumnMars from one bundle key."""

        def _arr(field):
            k = f"{key}__{field}"
            return d[k] if k in d else None

        def _scalar(field):
            k = f"{key}__{field}"
            if k not in d:
                return None
            v = d[k]
            return float(v) if np.ndim(v) == 0 else float(v.flat[0])

        z_km  = _arr("z_km")
        T_K   = _arr("T_K")
        P_Pa  = _arr("P_Pa")

        if z_km is None or T_K is None or P_Pa is None:
            raise ValueError(
                f"Required arrays (z_km, T_K, P_Pa) missing for key '{key}'."
            )

        # Volume mixing ratios — MCD stores these as e.g. 'vmr_co2'
        # We store them without prefix for consistency with atmosphere_earth.py
        vmr = {}
        _VMR_MAP = {
            "vmr_co2": "CO2", "vmr_n2": "N2",  "vmr_ar": "Ar",
            "vmr_co" : "CO",  "vmr_o2": "O2",  "vmr_o3": "O3",
            "vmr_h2o": "H2O",
        }
        for mcd_key, species in _VMR_MAP.items():
            arr = _arr(mcd_key)
            if arr is not None:
                vmr[species] = arr

        # sigma_T from rmst if available, else sigma_T array
        sigma_T = _arr("sigma_T")
        rmst    = _arr("rmst")
        if rmst is not None and not np.all(np.isnan(rmst)):
            sigma_T = rmst

        # Extra arrays and scalars
        extra = {}
        _EXTRA_ARRAYS = ["rho", "pscaleheight", "Cp", "Rgas"]
        _EXTRA_SCALARS = [
            "col_co2", "col_o3", "col_h2ovapor",
            "tsurf", "ps", "localtime", "lon",
        ]
        for f in _EXTRA_ARRAYS:
            arr = _arr(f)
            if arr is not None:
                extra[f] = arr
        for f in _EXTRA_SCALARS:
            v = _scalar(f)
            if v is not None:
                extra[f] = v

        ls_val = _scalar("ls")

        return cls(
            z_km           = z_km,
            T_K            = T_K,
            P_Pa           = P_Pa,
            vmr            = vmr,
            n_total        = _arr("n_total"),
            sigma_T        = sigma_T,
            tauref         = _scalar("tauref"),
            dod            = _scalar("dod"),
            tsurf_K        = _scalar("tsurf_K"),
            ps_Pa          = _scalar("ps_Pa"),
            fluxsurf_dn_sw = _scalar("fluxsurf_dn_sw"),
            fluxtop_dn_sw  = _scalar("fluxtop_dn_sw"),
            ls             = ls_val,
            lat            = _scalar("lat"),
            lon            = _scalar("lon"),
            dust_code      = dust_code,
            dust_label     = dust_label,
            source         = MarsAtmosphericSource.MCD_BUNDLED,
            extra          = extra,
        )

    @classmethod
    def from_npz(cls, path: str) -> "AtmosphericColumnMars":
        """
        Load a single MCD profile npz produced by
        scripts/convert_mcd_webapi.py (--output flag, not bundled).

        Parameters
        ----------
        path : str
            Path to the .npz file.
        """
        if not os.path.exists(path):
            raise FileNotFoundError(f"MCD profile file not found: {path}")

        data = np.load(path, allow_pickle=True)

        def _get(key, default=None):
            if key not in data.files:
                return default
            v = data[key]
            if np.ndim(v) == 0:
                return float(v)
            if v.shape == (1,):
                try:
                    return float(v[0])
                except (TypeError, ValueError):
                    return str(v[0])
            return v

        vmr = {}
        _VMR_MAP = {
            "vmr_co2": "CO2", "vmr_n2": "N2",  "vmr_ar": "Ar",
            "vmr_co" : "CO",  "vmr_o2": "O2",  "vmr_o3": "O3",
            "vmr_h2o": "H2O",
        }
        for mcd_key, species in _VMR_MAP.items():
            if mcd_key in data.files:
                vmr[species] = data[mcd_key]

        sigma_T = data["sigma_T"] if "sigma_T" in data.files else None
        rmst    = data["rmst"]    if "rmst"    in data.files else None
        if rmst is not None and not np.all(np.isnan(rmst)):
            sigma_T = rmst

        extra = {}
        for key in data.files:
            if key not in (
                "z_km", "T_K", "P_Pa", "n_total", "sigma_T", "rmst",
                "tauref", "dod", "tsurf_K", "ps_Pa",
                "fluxsurf_dn_sw", "fluxtop_dn_sw",
                "ls", "lat", "lon", "dust_code", "dust_label",
                "source", "mcd_version",
            ) and not key.startswith("vmr_"):
                extra[key] = data[key]

        dust_code  = int(_get("dust_code", 1))
        dust_label = str(data["dust_label"][0]) \
                     if "dust_label" in data.files else \
                     _BUNDLED_DUSTS.get(dust_code, "unknown")

        return cls(
            z_km           = data["z_km"],
            T_K            = data["T_K"],
            P_Pa           = data["P_Pa"],
            vmr            = vmr,
            n_total        = _get("n_total"),
            sigma_T        = sigma_T,
            tauref         = _get("tauref"),
            dod            = _get("dod"),
            tsurf_K        = _get("tsurf_K"),
            ps_Pa          = _get("ps_Pa"),
            fluxsurf_dn_sw = _get("fluxsurf_dn_sw"),
            fluxtop_dn_sw  = _get("fluxtop_dn_sw"),
            ls             = _get("ls"),
            lat            = _get("lat"),
            lon            = _get("lon"),
            dust_code      = dust_code,
            dust_label     = dust_label,
            source         = MarsAtmosphericSource.MCD_BUNDLED,
            extra          = extra,
        )

    # ══════════════════════════════════════════════════════════════════════════
    # Science methods
    # ══════════════════════════════════════════════════════════════════════════

    def column_density(self, species: str) -> float:
        """
        Vertical column density Ni = integral(xi(z)*n(z) dz),
        molecules/m^2. Trapezoidal integration.

        Returns 0.0 if species not present.
        """
        if species not in self.vmr:
            return 0.0
        z_m = self.z_km * 1e3
        return float(np.trapezoid(self.vmr[species] * self.n_total, z_m))

    def _mean_molecular_mass_at(self, idx: int) -> float:
        total_mass, total_frac = 0.0, 0.0
        for species, arr in self.vmr.items():
            mi = _MOLECULAR_MASS_KG.get(species)
            if mi is None:
                continue
            total_mass += arr[idx] * mi
            total_frac += arr[idx]
        if total_frac == 0.0:
            return 7.308e-26  # CO2 fallback
        return total_mass / total_frac

    def scale_height_at(self, z_km: float) -> u.Quantity:
        """
        Local scale height H(z) = kB*T(z) / (m_bar(z)*g).
        g is constant for Mars (small atmosphere relative to radius).
        """
        T_z = float(np.interp(z_km, self.z_km, self.T_K))
        total_mass, total_frac = 0.0, 0.0
        for species, arr in self.vmr.items():
            mi = _MOLECULAR_MASS_KG.get(species)
            if mi is None:
                continue
            xi = float(np.interp(z_km, self.z_km, arr))
            total_mass += xi * mi
            total_frac += xi
        m_bar = total_mass / total_frac if total_frac > 0 else 7.308e-26
        H_m = _kB * T_z / (m_bar * _g_mars)
        return (H_m * u.m).to(u.km)

    def effective_scale_height(self) -> u.Quantity:
        """
        Density-weighted effective scale height for Chapman function.

            H_eff = integral(n(z)*H(z) dz) / integral(n(z) dz)
        """
        H_z = np.array([
            self.scale_height_at(z).to(u.km).value for z in self.z_km
        ])
        z_m = self.z_km * 1e3
        num = np.trapezoid(self.n_total * H_z, z_m)
        den = np.trapezoid(self.n_total, z_m)
        return (num / den) * u.km

    # ══════════════════════════════════════════════════════════════════════════
    # Bridge to AtmosphericProfile (for RT module)
    # ══════════════════════════════════════════════════════════════════════════

    def to_profile(self, **overrides) -> AtmosphericProfile:
        """
        Build an AtmosphericProfile for the radiative transfer module.

        Uses this column's surface pressure, effective scale height,
        surface VMRs, and integrated column densities. Dust tau comes
        from tauref if available, otherwise falls back to the
        AtmosphericProfile.mars() default (0.5).

        Parameters
        ----------
        **overrides
            Any AtmosphericProfile field may be overridden.

        Returns
        -------
        AtmosphericProfile
        """
        surface_idx = 0

        composition = {
            sp: float(arr[surface_idx])
            for sp, arr in self.vmr.items()
            if sp in AtmosphericProfile._WELL_MIXED_SPECIES
        }

        column_densities = {
            sp: self.column_density(sp) for sp in self.vmr
        }

        # Use tauref from MCD if available
        dust_tau = self.tauref if self.tauref is not None else 0.5

        # Surface pressure from MCD ps_Pa if available, else P_Pa[0]
        surface_pressure = (
            self.ps_Pa * u.Pa if self.ps_Pa is not None
            else self.P_Pa[surface_idx] * u.Pa
        )

        defaults = dict(
            body                       = "mars",
            surface_pressure           = surface_pressure,
            scale_height               = self.effective_scale_height(),
            dust_tau                   = dust_tau,
            angstrom_exponent          = 1.0,
            single_scatter_albedo      = 0.93,
            composition                = composition,
            has_atmosphere             = True,
            column_densities           = column_densities,
            include_rayleigh           = True,
            rayleigh_king_factor       = 1.15,
            effective_refractive_index = 1.0004493,
            label                      = (
                f"Mars MCD | Ls={self.ls:.0f}° | "
                f"dust={self.dust_label} | tau={dust_tau:.3f}"
                if self.ls is not None else f"Mars MCD | {self.source.value}"
            ),
        )
        defaults.update(overrides)
        return AtmosphericProfile(**defaults)
